#Gradle
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Djdk.map.althashing.threshold=1048576
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=false

#Kotlin
kotlin.daemon.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Djdk.map.althashing.threshold=1048576
kotlin.native.binary.gc=cms

#https://youtrack.jetbrains.com/issue/KT-82395
kotlin.incremental.js=false
kotlin.incremental.js.klib=false

#Plugin
pluginVersion=0.0.2
