package dev.icedborn.spotube_plugin_piped.settings

import dev.icedborn.spotube_plugin_piped.client.json
import dev.icedborn.spotube_plugin_piped.store.EntityStore
import dev.krtirtho.plugin_interfaces.host_apis.SystemInformationAPI
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull

private const val REGION_KEY = "piped.region"

/** Stored value for "follow the system", the default. */
internal const val REGION_AUTO = ""
internal const val REGION_GLOBAL = "GLOBAL"

/** Countries YouTube publishes music charts for, by ISO code, with the name the chart titles use. */
internal val CHART_COUNTRIES: Map<String, String> = linkedMapOf(
    "AR" to "Argentina", "AU" to "Australia", "AT" to "Austria", "BE" to "Belgium", "BO" to "Bolivia",
    "BR" to "Brazil", "CA" to "Canada", "CL" to "Chile", "CO" to "Colombia", "CR" to "Costa Rica",
    "CZ" to "Czechia", "DK" to "Denmark", "DO" to "Dominican Republic", "EC" to "Ecuador", "EG" to "Egypt",
    "SV" to "El Salvador", "EE" to "Estonia", "FI" to "Finland", "FR" to "France", "DE" to "Germany",
    "GT" to "Guatemala", "HN" to "Honduras", "HK" to "Hong Kong", "HU" to "Hungary", "IS" to "Iceland",
    "IN" to "India", "ID" to "Indonesia", "IE" to "Ireland", "IL" to "Israel", "IT" to "Italy",
    "JP" to "Japan", "KE" to "Kenya", "LU" to "Luxembourg", "MY" to "Malaysia", "MX" to "Mexico",
    "NL" to "Netherlands", "NZ" to "New Zealand", "NI" to "Nicaragua", "NG" to "Nigeria", "NO" to "Norway",
    "PA" to "Panama", "PY" to "Paraguay", "PE" to "Peru", "PH" to "Philippines", "PL" to "Poland",
    "PT" to "Portugal", "RO" to "Romania", "RU" to "Russia", "SA" to "Saudi Arabia", "RS" to "Serbia",
    "SG" to "Singapore", "ZA" to "South Africa", "KR" to "South Korea", "ES" to "Spain", "SE" to "Sweden",
    "CH" to "Switzerland", "TW" to "Taiwan", "TZ" to "Tanzania", "TH" to "Thailand", "TR" to "Turkey",
    "UG" to "Uganda", "UA" to "Ukraine", "AE" to "United Arab Emirates", "GB" to "United Kingdom",
    "US" to "United States", "UY" to "Uruguay", "VN" to "Vietnam", "ZW" to "Zimbabwe",
)

// Time zone to country for the countries above, from tzdata zone.tab, plus common legacy aliases.
private val ZONE_COUNTRIES: Map<String, String> = mapOf(
    "Asia/Dubai" to "AE",
    "America/Argentina/Buenos_Aires" to "AR",
    "America/Argentina/Cordoba" to "AR",
    "America/Argentina/Salta" to "AR",
    "America/Argentina/Jujuy" to "AR",
    "America/Argentina/Tucuman" to "AR",
    "America/Argentina/Catamarca" to "AR",
    "America/Argentina/La_Rioja" to "AR",
    "America/Argentina/San_Juan" to "AR",
    "America/Argentina/Mendoza" to "AR",
    "America/Argentina/San_Luis" to "AR",
    "America/Argentina/Rio_Gallegos" to "AR",
    "America/Argentina/Ushuaia" to "AR",
    "Europe/Vienna" to "AT",
    "Australia/Lord_Howe" to "AU",
    "Antarctica/Macquarie" to "AU",
    "Australia/Hobart" to "AU",
    "Australia/Melbourne" to "AU",
    "Australia/Sydney" to "AU",
    "Australia/Broken_Hill" to "AU",
    "Australia/Brisbane" to "AU",
    "Australia/Lindeman" to "AU",
    "Australia/Adelaide" to "AU",
    "Australia/Darwin" to "AU",
    "Australia/Perth" to "AU",
    "Australia/Eucla" to "AU",
    "Europe/Brussels" to "BE",
    "America/La_Paz" to "BO",
    "America/Noronha" to "BR",
    "America/Belem" to "BR",
    "America/Fortaleza" to "BR",
    "America/Recife" to "BR",
    "America/Araguaina" to "BR",
    "America/Maceio" to "BR",
    "America/Bahia" to "BR",
    "America/Sao_Paulo" to "BR",
    "America/Campo_Grande" to "BR",
    "America/Cuiaba" to "BR",
    "America/Santarem" to "BR",
    "America/Porto_Velho" to "BR",
    "America/Boa_Vista" to "BR",
    "America/Manaus" to "BR",
    "America/Eirunepe" to "BR",
    "America/Rio_Branco" to "BR",
    "America/St_Johns" to "CA",
    "America/Halifax" to "CA",
    "America/Glace_Bay" to "CA",
    "America/Moncton" to "CA",
    "America/Goose_Bay" to "CA",
    "America/Blanc-Sablon" to "CA",
    "America/Toronto" to "CA",
    "America/Iqaluit" to "CA",
    "America/Atikokan" to "CA",
    "America/Winnipeg" to "CA",
    "America/Resolute" to "CA",
    "America/Rankin_Inlet" to "CA",
    "America/Regina" to "CA",
    "America/Swift_Current" to "CA",
    "America/Edmonton" to "CA",
    "America/Cambridge_Bay" to "CA",
    "America/Inuvik" to "CA",
    "America/Vancouver" to "CA",
    "America/Creston" to "CA",
    "America/Dawson_Creek" to "CA",
    "America/Fort_Nelson" to "CA",
    "America/Whitehorse" to "CA",
    "America/Dawson" to "CA",
    "Europe/Zurich" to "CH",
    "America/Santiago" to "CL",
    "America/Coyhaique" to "CL",
    "America/Punta_Arenas" to "CL",
    "Pacific/Easter" to "CL",
    "America/Bogota" to "CO",
    "America/Costa_Rica" to "CR",
    "Europe/Prague" to "CZ",
    "Europe/Berlin" to "DE",
    "Europe/Busingen" to "DE",
    "Europe/Copenhagen" to "DK",
    "America/Santo_Domingo" to "DO",
    "America/Guayaquil" to "EC",
    "Pacific/Galapagos" to "EC",
    "Europe/Tallinn" to "EE",
    "Africa/Cairo" to "EG",
    "Europe/Madrid" to "ES",
    "Africa/Ceuta" to "ES",
    "Atlantic/Canary" to "ES",
    "Europe/Helsinki" to "FI",
    "Europe/Paris" to "FR",
    "Europe/London" to "GB",
    "America/Guatemala" to "GT",
    "Asia/Hong_Kong" to "HK",
    "America/Tegucigalpa" to "HN",
    "Europe/Budapest" to "HU",
    "Asia/Jakarta" to "ID",
    "Asia/Pontianak" to "ID",
    "Asia/Makassar" to "ID",
    "Asia/Jayapura" to "ID",
    "Europe/Dublin" to "IE",
    "Asia/Jerusalem" to "IL",
    "Asia/Kolkata" to "IN",
    "Atlantic/Reykjavik" to "IS",
    "Europe/Rome" to "IT",
    "Asia/Tokyo" to "JP",
    "Africa/Nairobi" to "KE",
    "Asia/Seoul" to "KR",
    "Europe/Luxembourg" to "LU",
    "America/Mexico_City" to "MX",
    "America/Cancun" to "MX",
    "America/Merida" to "MX",
    "America/Monterrey" to "MX",
    "America/Matamoros" to "MX",
    "America/Chihuahua" to "MX",
    "America/Ciudad_Juarez" to "MX",
    "America/Ojinaga" to "MX",
    "America/Mazatlan" to "MX",
    "America/Bahia_Banderas" to "MX",
    "America/Hermosillo" to "MX",
    "America/Tijuana" to "MX",
    "Asia/Kuala_Lumpur" to "MY",
    "Asia/Kuching" to "MY",
    "Africa/Lagos" to "NG",
    "America/Managua" to "NI",
    "Europe/Amsterdam" to "NL",
    "Europe/Oslo" to "NO",
    "Pacific/Auckland" to "NZ",
    "Pacific/Chatham" to "NZ",
    "America/Panama" to "PA",
    "America/Lima" to "PE",
    "Asia/Manila" to "PH",
    "Europe/Warsaw" to "PL",
    "Europe/Lisbon" to "PT",
    "Atlantic/Madeira" to "PT",
    "Atlantic/Azores" to "PT",
    "America/Asuncion" to "PY",
    "Europe/Bucharest" to "RO",
    "Europe/Belgrade" to "RS",
    "Europe/Kaliningrad" to "RU",
    "Europe/Moscow" to "RU",
    "Europe/Simferopol" to "UA",
    "Europe/Kirov" to "RU",
    "Europe/Volgograd" to "RU",
    "Europe/Astrakhan" to "RU",
    "Europe/Saratov" to "RU",
    "Europe/Ulyanovsk" to "RU",
    "Europe/Samara" to "RU",
    "Asia/Yekaterinburg" to "RU",
    "Asia/Omsk" to "RU",
    "Asia/Novosibirsk" to "RU",
    "Asia/Barnaul" to "RU",
    "Asia/Tomsk" to "RU",
    "Asia/Novokuznetsk" to "RU",
    "Asia/Krasnoyarsk" to "RU",
    "Asia/Irkutsk" to "RU",
    "Asia/Chita" to "RU",
    "Asia/Yakutsk" to "RU",
    "Asia/Khandyga" to "RU",
    "Asia/Vladivostok" to "RU",
    "Asia/Ust-Nera" to "RU",
    "Asia/Magadan" to "RU",
    "Asia/Sakhalin" to "RU",
    "Asia/Srednekolymsk" to "RU",
    "Asia/Kamchatka" to "RU",
    "Asia/Anadyr" to "RU",
    "Asia/Riyadh" to "SA",
    "Europe/Stockholm" to "SE",
    "Asia/Singapore" to "SG",
    "America/El_Salvador" to "SV",
    "Asia/Bangkok" to "TH",
    "Europe/Istanbul" to "TR",
    "Asia/Taipei" to "TW",
    "Africa/Dar_es_Salaam" to "TZ",
    "Europe/Kyiv" to "UA",
    "Africa/Kampala" to "UG",
    "America/New_York" to "US",
    "America/Detroit" to "US",
    "America/Kentucky/Louisville" to "US",
    "America/Kentucky/Monticello" to "US",
    "America/Indiana/Indianapolis" to "US",
    "America/Indiana/Vincennes" to "US",
    "America/Indiana/Winamac" to "US",
    "America/Indiana/Marengo" to "US",
    "America/Indiana/Petersburg" to "US",
    "America/Indiana/Vevay" to "US",
    "America/Chicago" to "US",
    "America/Indiana/Tell_City" to "US",
    "America/Indiana/Knox" to "US",
    "America/Menominee" to "US",
    "America/North_Dakota/Center" to "US",
    "America/North_Dakota/New_Salem" to "US",
    "America/North_Dakota/Beulah" to "US",
    "America/Denver" to "US",
    "America/Boise" to "US",
    "America/Phoenix" to "US",
    "America/Los_Angeles" to "US",
    "America/Anchorage" to "US",
    "America/Juneau" to "US",
    "America/Sitka" to "US",
    "America/Metlakatla" to "US",
    "America/Yakutat" to "US",
    "America/Nome" to "US",
    "America/Adak" to "US",
    "Pacific/Honolulu" to "US",
    "America/Montevideo" to "UY",
    "Asia/Ho_Chi_Minh" to "VN",
    "Africa/Johannesburg" to "ZA",
    "Africa/Harare" to "ZW",
    "Asia/Calcutta" to "IN",
    "Europe/Kiev" to "UA",
    "Asia/Saigon" to "VN",
    "America/Buenos_Aires" to "AR",
    "Asia/Istanbul" to "TR",
)

private fun countryOfZone(zone: String): String? = when {
    zone.startsWith("US/") -> "US"
    zone.startsWith("Canada/") -> "CA"
    else -> ZONE_COUNTRIES[zone]
}

/** The chart region: the user's pick in the plugin settings, or a guess from the system time zone. */
internal class RegionSetting(private val store: EntityStore, private val systemInfo: SystemInformationAPI?) {

    suspend fun stored(): String =
        (store.get(REGION_KEY) as? JsonPrimitive)?.contentOrNull?.takeIf { it == REGION_GLOBAL || it in CHART_COUNTRIES }
            ?: REGION_AUTO

    suspend fun set(code: String) {
        val value = code.takeIf { it == REGION_GLOBAL || it in CHART_COUNTRIES } ?: REGION_AUTO
        if (value == REGION_AUTO) store.remove(REGION_KEY) else store.put(REGION_KEY, JsonPrimitive(value))
    }

    /** Country code for "Auto", or null when the system gives nothing usable. */
    fun detected(): String? {
        // TODO: read the country from getLocale() first once the host stops hardcoding it to "en-US".
        val zone = runCatching { systemInfo?.getTimeZone() }.getOrNull() ?: return null
        return countryOfZone(zone)?.takeIf { it in CHART_COUNTRIES }
    }

    /** ISO code of the charts to show, or [REGION_GLOBAL]. */
    suspend fun resolved(): String = when (val code = stored()) {
        REGION_AUTO -> detected() ?: REGION_GLOBAL
        else -> code
    }
}
